---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-config
  namespace: default
data:
  SIGNUPS_ALLOWED: "false"
  ADMIN_TOKEN: A+VjK9w+/070evyqMEhFcyvOySfdJm06vcFL0UmPMXUxyzA1dPQ8TcCkJ4ntjSl6
  DAOMIN: https://vault.buc.sh
  USER_ATTACHMENT_LIMIT: "1"
  ORG_ATTACHMENT_LIMIT: "1"
  INVITATIONS_ALLOWED: "true"
  INVITATION_ORG_NAME: "BUC Password Manager"
  IP_HEADER: X-Forwarded-For

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
      - name: vaultwarden
        image: ghcr.io/dani-garcia/vaultwarden:1.34.3
        envFrom:
        - configMapRef:
            name: vaultwarden-config
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          privileged: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: vaultwarden-data
          mountPath: /data
      volumes:
      - name: vaultwarden-data
        persistentVolumeClaim:
          claimName: vaultwarden-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: default
spec:
  selector:
    app: vaultwarden
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare-dns
spec:
  tls:
  - hosts:
    - vault.buc.sh
    secretName: cert-vault-buc-sh
  rules:
    - host: vault.buc.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vaultwarden
                port:
                  number: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

