
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.external-secrets.io

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 5m
  releaseName: external-secrets
  targetNamespace: default
  chart:
    spec:
      chart: external-secrets
      version: '0.x'
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      interval: 5m
  values:
    serviceAccount:
      name: external-secrets
