apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-cloudflare-dns
spec:
  secretStoreRef:
    name: k8s-vault
    kind: ClusterSecretStore
  refreshInterval: "1h"
  # Data defines the connection between the Kubernetes Secret keys and the Provider data
  data:
    - secretKey: token
      remoteRef:
        key: secret/saas/cloudflare
        property: cf_tunnel_token
