---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secrets
  namespace: default
spec:
  encryptedData:
    cf_apikey_dnsedit: AgCUjJQ+T++VcjCtMgf4HCTAiBGnliouxlh7QxnoH8P/39fR17aTP3UTtQI9q7pvVAewKpjIqwiN6WH1ygVy/Oxo7wLIzZ7ydg8prW+Q8ZymjkWSlKKTGqZoTCdS0UPaiFloRYI0+yuiaiV+lZs3vQRSPH4TVPTgsZzwKeWgiY+c2ylXzXjp4pXQKE/jivSbbItJl8ir2PX6bMRixnK/lXe0k5XxqVU0WnztgLNFIUyF9P1g7gj5T+UvQLYwFxDhXxZLihg/eqIzU/reG5zAiDYWD+nDEZflPegBAfGkVW8U3aC7ArNdz9MQWHlQxGqITR2TbMgGY2JxXxSjoF9FVJsU2295YvtbjwX9++ROtnWRbCUj/Hu7QZ/mez8dWoPgdMjyo7mnpQtkDt1NzoG0gOT+AxzVNcnC9wVroKVStBfCiHJpdZFZ0UwyGw0Y1LLGytVBbZnU8rGhtgsnN82R5RE1IvYU9fskfqBG5In1dAaTjUk9Rzdpl2EHM+o8fWgjInASeK5vufD6lfj+XAjjltPEysSdd5IGB/SdR9ur55F/03RmpY8ifHDNVhOHLJL/+8ga//YXgGM7dTAoYZK0BpM98hZctshu7+NrGmpnBMMrklugfTQg6bdFRSijP0pZPNEtVHnbw5p8zUsrL5WflBJqfzZ4qsc9YYhQwIxzIqYrzbOrz6MJV458GmzYOPvR4e0wbtbw989QItOq5SiG0D7qsIlLQt9O6yKUnWEO/54OtaODRAEHtTSD
    cf_tunnel_token: AgAARM7jAXK6ofyBVIkN/V17zexX/1hgOMkIfDMLn6LYDRJtk/uNsGZqCFgznUrilpDuSt5RZkeJdy/l10lxQCG00LhdRojuEyqUZzGYUvZ1NYeKlbpVen5O7S6ihwmcjPfzkbjmPr/HXt4UKgo3w8155nyWKb6CkWYNAoanbWlg8TMMQH4c3VQDuW42fLjkLGLmwInEZVU6TFouu3kmJi2B5wFTaMOqLFJHSGGpNL2nmcwpDkQtHjmvasUj9KYckuFYm+53eOX5vPBSc+qeDuWSBgh5uIpkZSCajkDDZwNl1izOVjfTAWt4jzmxpJm/kDhuCMhx3k2fW/SQWnjZvuR56YcxUB6oD0Fa7XlBDCO2nLQ8T/E4FFxhBPr+mfG4vEdy2MGzyS2eRRe0pKPvjbKEjEUJxmtnlgDQVHPHZwrY52hyeHmIhIj357/Uhd9UslY0j+efcvHoiaX84HwnSXCiLetYZLGAxxj1VHNGeOPw3IQM5xtyNWUf+4fdEJn/CG+48fSJCubhpvRTXTt9rEdI61XKTRRFht45nGoeY2uj2bdrYa32s5ZdV32J49s3s3/VwJMK6bMcREgZWgc+3Xrb8bI4wMchlsUM3nZPSxJjyap0C5CqalE4v9mrxMbLLsIbQz2MitQcSBivLthhWUhhue0bWL6LOd9sVn2i/wCYDlunVzyfb6wLfpqdZcyuxgSgdyxaEBZpPqlgBt0bPI30eSGa7l0Z8ywYXJV+aNdQoL97quwMBoqj9FyG54iiTWuOvuIfUisxBH1KW5tiaARPzLXJWeNPW8MXKi/HypqDjljkGIhlbfNtCEjPKYxwfFBOmus+Z7xYk6IPkSpUxEY2X5b62Fa05gYpKxLBnqhGRvZy46A2s65Ltw1+3XrNits0/y3ixeND48/APHQccybS6LQr7faFQsk8ddXSaPK/+A+/U1O3/OWW
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secrets
      namespace: default
