---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-terraform-admin
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-terraform-admin
subjects:
- kind: ServiceAccount
  name: vault-terraform-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: tf-runner-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authorize-tf-controller-in-namespace
subjects:
- kind: ServiceAccount
  name: tf-controller
  namespace: flux-system
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: tf-controller-role
  apiGroup: rbac.authorization.k8s.io