---
apiVersion: v1
kind: Secret
metadata:
  name: ss-key
  namespace: kube-system
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active
type: kubernetes.io/tls
stringData:
  tls.crt: ""
  tls.key: ""

