
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gatus
  namespace: flux-system
spec:
  interval: 24h
  url: https://minicloudlabs.github.io/helm-charts

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gatus-status
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare-dns
spec:
  tls:
  - hosts:
    - gatus.buc.sh
    secretName: cert-gatus-buc-sh
  rules:
  - host: gatus.buc.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gatus
            port:
              number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gatus-status-http
  namespace: default
spec:
  rules:
  - host: gatus.10.0.0.16.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gatus
            port:
              number: 80



---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: flux-system
spec:
  interval: 5m
  releaseName: gatus
  targetNamespace: default
  chart:
    spec:
      chart: gatus
      version: '>=3.2.0'
      sourceRef:
        kind: HelmRepository
        name: gatus
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: gatus-values
    valuesKey: config