---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: flux-system
spec:
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
        - apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: authelia
            namespace: default
          spec:
            template:
              spec:
                initContainers:
                - name: inject-passwords
                  image: ghcr.io/authelia/authelia:latest
                  command:
                  - sh
                  - -c
                  - |
                    cp /users-template/users_database.yaml /users/users_database.yaml;
                    ADMIN_HASH=$(authelia crypto hash generate argon2 --password "$cred_admin_password" | awk '{ print $2 }');
                    sed -i -e "s#__REPLACE_ME_ADMIN__#$ADMIN_HASH#" /users/users_database.yaml;
                    echo "Set password for $cred_admin_user";
                    BUC_HASH=$(authelia crypto hash generate argon2 --password "$cred_user_password" | awk '{ print $2 }');
                    sed -i -e "s#__REPLACE_ME_BUC__#$BUC_HASH#" /users/users_database.yaml;
                    echo "Set password for $cred_user_user";
                    EXTERNAL_HASH=$(authelia crypto hash generate argon2 --password "$cred_externalhttp_password" | awk '{ print $2 }');
                    sed -i -e "s#__REPLACE_ME_EXTERNAL__#$EXTERNAL_HASH#" /users/users_database.yaml;
                    echo "Set password for $cred_externalhttp_user";
                    cat /users/users_database.yaml;
                  envFrom:
                  - secretRef:
                      name: common-secrets
                  volumeMounts:
                    - name: config
                      readOnly: true
                      mountPath: /configuration.yaml
                      subPath: configuration.yaml
                    - name: user-database-replaced
                      readOnly: false
                      mountPath: /users
                    - name: user-database-configmap
                      readOnly: true
                      mountPath: /users-template
