---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: voodoo-gitops
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/thomasbuchinger/voodoo-gitops
  ref:
    branch: to_be_replaced

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: voodoo-gitops
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./gitops
  prune: true
  sourceRef:
    kind: GitRepository
    name: voodoo-gitops
  targetNamespace: default