---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: voodoo-gitops
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/thomasbuchinger/voodoo-gitops
  ref:
    branch: main

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-manifests
  namespace: flux-system
spec:
  interval: 15m
  path: ./gitops/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: voodoo-gitops
  targetNamespace: flux-system