apiVersion: v1
kind: Namespace
metadata:
  name: prod-secrets

---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: prod-eso-auth
  namespace: prod-secrets

---
apiVersion: v1
kind: Secret
metadata:
  name: prod-eso-auth-token
  namespace: prod-secrets
  annotations:
    kubernetes.io/service-account.name: prod-eso-auth
type: kubernetes.io/service-account-token

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eso-secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-secret-reader
  namespace: prod-secrets
subjects:
- kind: ServiceAccount
  name: prod-eso-auth
  namespace: prod-secrets
roleRef:
  kind: ClusterRole
  name: eso-secret-reader
  apiGroup: rbac.authorization.k8s.io