apiVersion: v1
kind: Namespace
metadata:
  name: prod-secrets

---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: prod-eso-auth
  namespace: prod-secrets

---
apiVersion: v1
kind: Secret
metadata:
  name: prod-eso-auth-token
  namespace: prod-secrets
  annotations:
    kubernetes.io/service-account.name: prod-eso-auth
type: kubernetes.io/service-account-token

