apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: pi-hole
  namespace: kube-system
spec:
  repo: https://charts.truecharts.org
  chart: pihole
  targetNamespace: pi-hole
  valuesContent: |-
    image:
      tag: master
    env:
      GF_EXPLORE_ENABLED: true
    adminUser: admin
    sidecar:
      datasources:
        enabled: true
