apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-admin
  namespace: default
spec:
  encryptedData:
    password: AgCspyRs2Y9/albDMG9Knmpaah7cOhBr+xc9y115euuFI/okLwgonTg2dB44fY7dMTLsoSQPiyKORPuCZn1Ni5J+K0X/i6M6SuHWSUYi7rZACiRrAscJbfEPWuXxUUXgYLqpWdkhAdP+p2jADNXV5tJp1peoH3TU1OGm9IyEDA/MNetqDEyawE6PtWBfNRPVNQDQbaU9UjWRsGAbnWgk0JBRORkBiKKHC81HJo+r7MYoQXCDDzIOgdsFCM5JfGqq0xvFNaOVNn8id31alIuHgPfGcH5DJPVmmlF+McAlpCsuwQGUuqQqcKXEJP2yeXPX2/V75Ama3WhGNaLWFCzE0IG+te1TJwbqAMOlHLhd+vW7VnKpQW8u7pIVkNk129V+MefEK8gjmW/SgIxjgdp95z6SGVR6G5J2lNX9U3djU9e9txW7U1jXBbYknKMXJMteTKefp6jgtwE4SIdbVuMnH0ZmngRA5PHz4IOzqNYvhO3FHW4oIcqHtKqC9zKQMUyNgq8CCP2CQMzIww2Rah2dG8CR/5z8QJ2voGLPnGOHpkU/HtUHsimbpFPStNChnrmEedsYNi1UUIsAJgzVPZY2Xf9/UjJpQQjIzkvxZD90qxEGhaEJZBi3bHAtUPyNKlCOcL3c2C72k7mHvoRB+ujUcC1etQ+iJHG3I/C/1WmSRGBtpKOoKNU2EMtsmFSqQ8I8Wz2H8RphtJQBhDeOQB0L/3FSeuh3M+QACMdtHC2BL60drxU=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pihole-admin
      namespace: default

