apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-admin
  namespace: default
spec:
  encryptedData:
    password: AgBzIuUL7nSM1iULsWBMH5s7yisIR4CzL7S8pIy7Fgj/AgTo2XJiGmSAHI/9OPgHVY3mbgpqFy05RhBHxfBg0U82XPzknJH1nLFNmO/Bq9A1mNkydtkUrWO7/ddGTe0iIvsS/AKNvi1hUgNuwRuoY+y7CgImDT8mxnstKLTHXtPba0sNElkVVB7Uohjp7hf9ZCGI+48mCn7YODVlR7wTD/0tcBdQcTYhma8h8HrIpfVYz9UmasSh5+hu0mT6CyS/m9zO6fqXQzi9Pi/iT/RBdRdQYPpJUnwpdspTZ08TvszxfiSs+amOdImccGv+wAA18Iw7LfAFgNCLTkq3f1UVEtC//ZkcP+Ka5LUUyFtglk2d5Ze38NjDlmjny80H82aZFyEUTGtkbT8NjlHZd1jekfcB1UedktMMgDQbNpBnlLuI2R3SheXbFIx9irC83szzVMzaxHoPBrozzStqEGbnVhAJ80K8UHttCMYxVEncN44jkkwsvsc2FwoTkJLbGBVV1+McPQ1BDGSuTAjmfvlX+Dr+5jWFteGz8s8qTnPB+VL8rzBeD896LUi6QjdbEwhnOQ+VHVYTU+v4YyxYAPoP0Hbo2mtD0W/R9ddLUfbVnzH4knhKsqg5hZPyCFiUCNcM5bcSQYH5FwRrE+QfMSecCEjhZmKB0Z1lKYXgfZoGoCu59tDbud/mni5eMJ6LGlxmX0f3SuXJtTOY/2VMdGzF9TKMMYbnlSnBMSb73jWg4gYzxF8=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pihole-admin
      namespace: default

