
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: pihole
  namespace: flux-system
spec:
  interval: 24h
  url: https://mojo2600.github.io/pihole-kubernetes

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: flux-system
spec:
  interval: 5m
  releaseName: pihole
  targetNamespace: default
  chart:
    spec:
      chart: pihole
      version: '>=2.0.0'
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
      interval: 15m
  postRenderers:
  - kustomize:
      patchesJson6902:
      - target:
          version: v1
          kind: Deployment
          name: pihole
        patch:
        - op: add
          path: /spec/template/spec/containers/0/ports/4/hostPort
          value: 67
  values:
    image:
      tag: "latest"
    dnsHostPort:
      enabled: true
    serviceDns:
      mixedService: true
      type: ClusterIP
    serviceDhcp:
      enabled: true
      type: ClusterIP
    # serviceWeb: {}
    virtualHost: pihole.buc.sh
    ingress:
      enabled: false
    admin:
      existingSecret: common-secrets
      passwordKey: cred_admin_password
    dnsmasq:
      customDnsEntries:
      - address=/nas.buc.sh/10.0.0.19
      - address=/kvm.buc.sh/10.0.0.13
      - address=/evergreen.buc.sh/10.0.0.16
      - address=/kube.buc.sh/10.0.0.20
      - address=/prod.buc.sh/10.0.0.32
      - address=/green-prod.buc.sh/10.0.0.33
      - address=/bastion.buc.sh/10.0.0.101

      # Workaround
      - address=/vault.buc.sh/10.0.0.16
      customCnameEntries:
      - cname=s3.buc.sh,nas.buc.sh
      - cname=sync.buc.sh,nas.buc.sh
      - cname=pihole.buc.sh,evergreen.buc.sh
      - cname=paste.buc.sh,evergreen.buc.sh
      # - cname=vault.buc.sh,evergreen.buc.sh
      - cname=wireguard.buc.sh,evergreen.buc.sh
      - cname=evergreen-console.buc.sh,evergreen.buc.sh
      - cname=auth.buc.sh,evergreen.buc.sh
      - cname=argocd.buc.sh,green-prod.buc.sh
      - cname=grafana.buc.sh,green-prod.buc.sh
      - cname=paperless.buc.sh,green-prod.buc.sh
      
      customSettings:
      # DHCP Settings. (Raw dnsmasq config)
      - interface=eth0
      - shared-network=eth0,10.0.0.0
      - shared-network=10.42.0.0,10.0.0.0
      - log-dhcp
      - dhcp-authoritative
      - dhcp-leasefile=/tmp/dhcp.leases
      - dhcp-range=10.0.0.150,10.0.0.199,255.255.255.0,24h
      - dhcp-option=option:router,10.0.0.1
      - dhcp-option=option:dns-server,10.0.0.16
      - dhcp-option=option:dns-server,10.0.0.1
      - dhcp-option=option:dns-server,8.8.8.8
    # DHCP needs NET_ADMIN
    capabilities:
      add:
      - NET_ADMIN
    # # DHCP needs a volume for dhcp leases
    # extraVolumes:
    #   dhcpleases:
    #     emptyDir: {}
    # extraVolumeMounts:
    #   dhcpleases:
    #     mountPath: /var/lib/misc
        

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare-dns
spec:
  tls:
  - hosts:
    - pihole.buc.sh
    secretName: cert-pihole-buc-sh
  rules:
  - host: pihole.buc.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pihole-web
            port:
              number: 80
  - host: pihole.10.0.0.16.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pihole-web
            port:
              number: 80