apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-admin
  namespace: default
spec:
  encryptedData:
    password: AgCPKaryDacMNWvLv5bUZGsTmxtGz5xVY74Yn7JUqDYDEfrZLn/M244xTVg+qPRng7TrakcC576BsUfukFVHBA+J/DGC7/7jI1U9h9i87MdjC//dxI93rz01oy37TDBtwtZvhGeCZGXQ9dHkiCU6+QKAjFAsCdJMEekBomBj0Nr4QUlaUvV6MXh2PatGdf2JPDAs7tKK4UEM11Kon3aqgsRRI9297YJwJaqso89OcvgH6T9NcJuraWcgt9N9aPH4EAQK+/FGBz7JRWDhHFsHRXgkTmTK89pPBI6+oBp6VkF0VfAPDlMMKKcE9DP2UuMNP3QkwImV7t9AC3+FnUtdQLxhWQdEXs+i9YHw4qwHjG7XNP62ecgiTxg6CgZUdm51vv5XjI87DFEp8+5Rh1wEzdEpNkoiPtWA2VWJ2pG1Fev0lUm6IAa+rR+jhxOMS1AFBsmKai+Se1LCfyukLzzC1dEgXm9+lWuhtfpQEX41MOWASG7y+mgWOezAq39Eo03DnOwVX0cn+f/qgmOiR2NsEVxFXSXDUPYip2YozmcfBFXzJOjd5lrIOk8GByyn439D0ScAVAEEdjw6jNFcam1Ya428i8jh8NZqkUfxsYsesVXdgxZADfXya2hqsdWcI4lb9SazLq49Z62JIqBVIEtsB2ZfPINVZy36jvgOTXQJANCF4Nx9o8zRX24JXs1xF/si6oJBZSHXx9sq2I8eOZVWQTg+zUO1dheesgBWJrKcwZ3+ME0=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pihole-admin
      namespace: default

