
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: pihole
  namespace: flux-system
spec:
  interval: 24h
  url: https://mojo2600.github.io/pihole-kubernetes

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: flux-system
spec:
  interval: 5m
  releaseName: pihole
  targetNamespace: default
  chart:
    spec:
      chart: pihole
      version: '>=2.0.0'
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
      interval: 15m
  values:
    image:
      tag: "latest"
    # Move HTTP Ports to avoid conflicts with ingress-controller
    webHttp: 8000
    webHttps: 8443
    serviceDns:
      mixedService: true
      type: ClusterIP
    serviceDhcp:
      enabled: false
    virtualHost: pihole.buc.sh
    ingress:
      enabled: false
    admin:
      existingSecret: common-secrets
      passwordKey: cred_admin_password
    monitoring.sidecar.enabled: true
    extraEnvVars:
      FTLCONF_LOCAL_IPV4: 10.0.0.16
    dnsmasq:
      customDnsEntries:
      - address=/kvm.buc.sh/10.0.0.13
      - address=/evergreen.buc.sh/10.0.0.16
      - address=/nas.buc.sh/10.0.0.20
      - address=/prod.buc.sh/10.0.0.21
      - address=/secure-http.buc.sh/10.0.0.22
      - address=/green-prod.buc.sh/10.0.0.33
      - address=/bastion.buc.sh/10.0.0.101

      # Workaround
      - address=/vault.buc.sh/10.0.0.16
      customCnameEntries:
      # evergreen.buc.sh
      - cname=pihole.buc.sh,evergreen.buc.sh
      - cname=paste.buc.sh,evergreen.buc.sh
      - cname=status.buc.sh,evergreen.buc.sh
      - cname=gatus.buc.sh,evergreen.buc.sh
      - cname=evergreen-console.buc.sh,evergreen.buc.sh
      # prod.buc.sh
      - cname=argocd.buc.sh,prod.buc.sh
      - cname=grafana.buc.sh,prod.buc.sh
      - cname=auth.buc.sh,prod.buc.sh
      - cname=prod-console.buc.sh,prod.buc.sh
      - cname=paperless.buc.sh,prod.buc.sh
      - cname=syncthing.buc.sh,prod.buc.sh
      - cname=files.buc.sh,prod.buc.sh
      # prod-green.buc.sh
      # nas.buc.sh
      - cname=s3.buc.sh,nas.buc.sh
      - cname=sync.buc.sh,nas.buc.sh
      
      customSettings:
      # DHCP Settings.
      - dhcp-authoritative
      - dhcp-leasefile=/tmp/dhcp.leases
      - dhcp-range=10.0.0.150,10.0.0.199,255.255.255.0,24h
      - dhcp-option=option:router,10.0.0.1
      - dhcp-option=option:dns-server,10.0.0.16,10.0.0.1,8.8.8.8
      # Enable IPv6. Enable Router Advertisements, Only do RA (and not actually assign IPv6 addresses) with high priority
      - enable-ra
      - dhcp-range=tag:ip6,::1f,::ff,constructor:eth0
      - dhcp-option=option6:dns-server,[fe80::]
      - ra-param=eth0,high,60
      - dhcp-reply-delay=tag:ip6,5
    # DHCP needs NET_ADMIN and hostNetwork
    hostNetwork: true
    capabilities:
      add:
      - NET_ADMIN

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare-dns
spec:
  tls:
  - hosts:
    - pihole.buc.sh
    secretName: cert-pihole-buc-sh
  rules:
  - host: pihole.buc.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pihole-web
            port:
              number: 80
  - host: pihole.10.0.0.16.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pihole-web
            port:
              number: 80
