apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-admin
  namespace: default
spec:
  encryptedData:
    password: AgCkCmREjhI+oR71oqD+fekgJ0Uiwt/raQfott29IR0Gm9HUDRkc9lo10B36YoM9s96DPtNT+lJq4FT4Th2qMeeKEau5RTEJhKByf/t2MH1YPBnVTDXZnEgq49wT8QaPDwo13Y2a66KppjRLkLKcPbwaLNjaYeZbDU7m47OXcFi73wF2J6cLrYnSQKMLxhTQ4MgVPcVUxq1J91GAVaqemTtxMauIg1RwdhUezdlab02T2KERcsRqLhuRYHuMxw6Df34aQUf2/wp6nuMbLv8SObzmw685unRPYfG7ikPCnl0YaGpB9Ygx7En7yCUd8pJFojevY5zt87yXcoPjyc58NXBdFupxPdmd/FCFnEHJIoPCR7e6BFpWEeIyWZw1G+sd8sf+U3ELiTmImpJVTRBSz2skPRhrKMg6whgYq+lJcqcANwm4GZ1nZqyCL+zjOab0vrEl1L8e9dc0tWf+7pj+y/dIzEg8gBzLOlx5PxB+ZdD0VHXViEZoqQZwrsD5pGFTgIlA5nKAPdGuYAYvxWH7lrtwkPeOcn3ikFyZbeoNaiKBurLA0vYbqn33AlMel5H7Dp/ZilqNDKZ/6LIuz0Ov4Amq6umc56uyIRlTaHsni8OAnQW0N/Iv2e+7yxgdrvEUxATB0iVQ3wuqBE9ulqPHM1puafcfUlqYtA9afCtV2z+DhyAw8h4/LFpigOJBIAJBf344z15iVdqImafIuXqQQOz1vPBjBCyQCPvcX96+jiKDUaI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pihole-admin
      namespace: default

