apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: pihole
  namespace: kube-system
spec:
  repo: https://mojo2600.github.io/pihole-kubernetes
  chart: pihole
  targetNamespace: default
  valuesContent: |-
    image:
      tag: "2022.07"
    dnsHostPort:
      enabled: true
    serviceDns:
      mixedService: true
      type: ClusterIP
    serviceDhcp:
      enabled: false
    # serviceWeb: {}
    virtualHost: pihole.buc.sh
    ingress:
      enabled: true
      hosts:
      - pihole.buc.sh
      - pihole.10.0.0.16.nip.io
    admin:
      existingSecret: pihole-admin
      passwordKey: password
    dnsmasq:
      customEntries:
      - address=/nas.buc.sh/10.0.0.19
      - address=/kvm.buc.sh/10.0.0.13
      - address=/voodoo.buc.sh/10.0.0.16
      customCnameEntries:
      - cname=pihole.buc.sh,voodoo.buc.sh
