apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-admin
  namespace: default
spec:
  encryptedData:
    password: AgBP281w2qVibSA5LkRDL6TZmvf3wDS2sdn/qjvre8zsVbM9Dl8ZVsrfEs2yGJGLUnkhXFiipnX9ZdkZrqbBnChaHk6/APTfOMpl5Z/9gHzrnzt2EGB0ypqFdp3bsZHmq8Z9BbqluMkHe+PP2bOLBg1CseFmUWBNO+bmzYke4TzZ9je26MPkWX4u0lx4iWLhmLD8WR9F0ySXWEWfxRbY/oMobBgesbJxMWRyQjCdQwSzegWXHpGEQJ2F3tLc7ZbeACh1qv9VvlCfufFi6eYx5aso8dRU2Nymw0lTjrD0VmLQTitfgthCQQJ9lYkdlb9AC/JXAEeq9R47Awd26S0ROy5Qj0cUQziQJ93Wz6Gs52qqcuMeUrcLcv70hB6fTFKlueW8hv449x9vmxB11zd0NG6KMabviTuAWsDfaIXb6GGYMZvn1cACgGUD469W2tpEydHiljvbDy+4JJgIa3EF601U6lN4U6PKpJC7o5KoJRDl0n3eeB/Qbx15cMxse5WbJHDE92HpH6r94qN7BfWkzohOnSjTBYzFautCNr3iLf8bvwYOtTkpyh3U36ebJoWy4M0LN0lebHmTiuq6IRhRMKxCARrE2bLZb+0mF7xr9Obwuj/DjPxsCaUhTmIKzCZJYNi454VJ6mHR2Cqh2BXH2+BCS4cac8akrhQhjL3N1+ghA2Jw3QJgE6I9J1/pL1rtdveWm/0hVAjfjMAUpRBRqIR1vEDHURKo7ZnY5Y7RlixuYOg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pihole-admin
      namespace: default

