apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-admin
  namespace: default
spec:
  encryptedData:
    password: AgCaBgst5edZsYpV9OEPNqCrWZxMNX4mW6XVnGzG+DO5m3QZZx9e4mFWjFrrmO/4nHJJL+435lUmC2OlXuiz07H+TvuAayqoo9S2FZH3u0yJsYul/Iqfb196sBkKlQ1IYKS4NQK5ViWh7/e/5m11KHlo8WLT4IX6j7VGz8vBwRfIR8J+MBYRzMhits0dr0Y3jDo6y8Nop9b2HZdJ3QUmjhAVUeL5JJ5QUCgJY2ggoedtMxyyHj6pAyKZpHx5zbo/ME/Z5PFZPFBlhmYjxGp6CGoSAjZgJZJJQ6FvFFPVrY72qD/PTYO54IEWDex3gpdtTIN5rcy2dGCw8QdyV6wAIVmjnRrtqMbwcxNOL8T8XYChDZLIuJOczuxM4jPsEmX+Qgqh2P1er+uPoq8e+iRxJIt8Xq4AgxYBLVpZxFJy63p4gKxfy3kR4i4jb1EAvlz5eJgtkWySW5mqMJ2/aFTrIT8rAlGy4lPs7y2RTNGQlLhyK5B0yiGMfUV4uZlRT+mWHEibwJTrWBA+4wx66alTKJP4rDn82hW9WNRh/TIuu28aDNlNYbs0Y9Vgs2f34GArD+qTL2Bw2H8MAHQl5oZRfPw5aN/RmXdF2v9pOKeWR7OM3R2a/b8zCYmM3ucBRqedp5rgSq+smoUZf+xGm7k1p0PetQQ4P8ohjZUEQaFfPGgVZcF6nsE/m1a/j7kfkDtsrMdyzxav6BGNZ91HpPIoM+6Zv7xTAQ6lCmcjXh0Sh6mEjQw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pihole-admin
      namespace: default

