apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik-config
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        allowExternalNameServices: true
      kubernetesIngress:
        allowExternalNameServices: true
      kubernetesGateway: {}
    experimental:
      kubernetesGateway: true
