apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oidc-kubelogin
spec:
  secretStoreRef:
    name: k8s-vault-cluster
    kind: ClusterSecretStore
  refreshInterval: "1h"
  # Data defines the connection between the Kubernetes Secret keys and the Provider data
  data:
    - secretKey: client_id
      remoteRef:
        key: cluster/oidc/kubelogin
        property: client_id
    - secretKey: oidc_provider_url
      remoteRef:
        key: cluster/oidc/kubelogin
        property: oidc_provider_url
