---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vault-operator
  namespace: flux-system
spec:
  interval: 24h
  url:  https://kubernetes-charts.banzaicloud.com

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault-operator
  namespace: flux-system
spec:
  interval: 5m
  releaseName: vault-operator
  targetNamespace: default
  chart:
    spec:
      chart: vault-operator
      version: '>=1.0.0'
      sourceRef:
        kind: HelmRepository
        name: vault-operator
        namespace: flux-system
      interval: 5m
  values: {}
