
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kube-state-metrics
  namespace: flux-system
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: flux-system
spec:
  interval: 5m
  releaseName: kube-state-metrics
  targetNamespace: default
  chart:
    spec:
      chart: kube-state-metrics
      version: '>=3.0.0'
      sourceRef:
        kind: HelmRepository
        name: kube-state-metrics
        namespace: flux-system
      interval: 5m
  values: {}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expose-kube-state-metrics
  namespace: default
spec:
  rules:
  - host: "kube-state-metrics.10.0.0.16.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kube-state-metrics
            port:
              number: 8080