---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: buc-lenovo
  namespace: mtls
spec:
  isCA: false
  commonName: mtls-lenovo
  subject:
    organizations:
    - BUC LAB
    countries:
    - AT
  duration: 860h    # 365d
  renewBefore: 160h # 90d
  usages:
  - client auth
  - any
  # privateKey:
  #   algorithm: ECDSA
  #   size: 521
  #   rotationPolicy: Always
  secretName: mtls-buc-lenovo
  keystores:
    pkcs12:
      create: true
      password: "changeme"
      profile: LegacyDES
  issuerRef:
    name: buc-root-ca-mtls
    kind: Issuer
    group: cert-manager.io

  