apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: default
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  targetNamespace: default
  valuesContent: |-
    installCRDs: true
