apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: Vault
metadata:
  name: vault
spec:
  externalConfig:
    startupSecrets:
      - type: kv
        path: secret/data/saas/cloudflare
        data:
          data:
            cf_tunnel_token: "${env `cf_tunnel_token`}"
            cf_apikey_dnsedit: "${env `cf_apikey_dnsedit`}"
      - type: kv
        path: secret/data/saas/github
        data:
          data:
            github_username: "${env `github_username`}"
            github_apikey_image_updater: "${env `github_apikey_image_updater`}"
      - type: kv
        path: secret/data/saas/vault-cr-test2
        data:
          secretKeyRef:
          - name: vault-content-github
            key: github_username
            optional: true
          - name: vault-content-github
            key: github_apikey_image_updater
            optional: true
          - name: vault-content-does-notexist
            key: github_apikey_image_updater
            optional: true
      - type: kv
        path: secret/data/access/static-cred
        data:
          data:
            cred_description: "${env `cred_description`}"
            cred_admin_user: "${env `cred_admin_user`}"
            cred_admin_password: "${env `cred_admin_password`}"
            cred_user_user: "${env `cred_user_user`}"
            cred_user_password: "${env `cred_user_password`}"
      # - type: kv
      #   path: secret/data/cluster/minio/bucket-vault
      #   data:
      #     data:
      #       access_key: "${env `minio_vault_secret_key`}"
      #       secret_key: "${env `minio_vault_secret_key`}"
      
  envsConfig:
    - name: cf_tunnel_token
      valueFrom:
        secretKeyRef:
          name: vault-content-cloudflare
          key: cf_tunnel_token
          optional: true
    - name: cf_apikey_dnsedit
      valueFrom:
        secretKeyRef:
          name: vault-content-cloudflare
          key: cf_apikey_dnsedit
          optional: true
    - name: github_username
      valueFrom:
        secretKeyRef:
          name: vault-content-github
          key: github_username
          optional: true
    - name: github_apikey_image_updater
      valueFrom:
        secretKeyRef:
          name: vault-content-github
          key: github_apikey_image_updater
          optional: true
    - name: cred_description
      valueFrom:
        secretKeyRef:
          name: common-secrets
          key: cred_description
          optional: true
    - name: cred_admin_user
      valueFrom:
        secretKeyRef:
          name: common-secrets
          key: cred_admin_user
          optional: true
    - name: cred_admin_password
      valueFrom:
        secretKeyRef:
          name: common-secrets
          key: cred_admin_password
          optional: true
    - name: cred_user_user
      valueFrom:
        secretKeyRef:
          name: common-secrets
          key: cred_user_user
          optional: true
    - name: cred_user_password
      valueFrom:
        secretKeyRef:
          name: common-secrets
          key: cred_user_password
          optional: true
    # - name: minio_vault_access_key
    #   valueFrom:
    #     secretKeyRef:
    #       name: vault-s3
    #       key: access_key
    #       optional: true
    # - name: minio_vault_secret_key
    #   valueFrom:
    #     secretKeyRef:
    #       name: vault-s3
    #       key: secret_key
    #       optional: true

