apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vault-content-github
  namespace: default
spec:
  encryptedData:
    github_apikey_image_updater: AgBUoHZmywPmL6FYs/eIEIOyqFpu4XrMLz8xKB6kS1/LPSqjt0M3NfJEhLoeNFQNMAjDBHc+HSnkVHGW4zSho6XzJLhiTmgcJ4ghOziGgxeqaBvHLtqQy4W8tB4//zR0ugibLPhOBoJ3hGk3PBw7dzG1Nc2MU/MAaXDVqwUuzTXslerFDdW2d6W1dgSqu/etKH+bUhE6CqOq3TmZXFLvpthr8lSwCJg4WxpLDFasLIgyik0hRl9fxqXtKFOhdti9gSH3VWyohtRgE7cN+eZWnQD8bHpQYNPBdklbP05Us6B86j4EBCP5eE7lxZPmU0FRoBp2XovIXKIcgAvrTYI/Zg09R6z40v22tajEuoO9h8tFHE3E0vcjhz3Us/3SCDBaewm4psqBlXUjbjCFBqwn3N/L2+u9PIb9+YHG61p0eihR5c9CnyLCPmMaFJZtEIWYO8GDLoqGjT1gEAKzaYI2XIbWuGDcrZtk/V94cgvuri8LG+TJipqybnA2nwL32QYsfnMQhpyIISjDTpCwVdh5PD+iPi8p8avJ6/dTfewRupOfUWg82w5gYPemVLXhNugGoc7HJPww3kbTQfRDfUsC7NFI3q6SwpIB91pzcqBdIc1KfvvPpl2e6wJmHTgRYQv0YttgL8hXVPdGfkJ482TE9bTKBoRz1Q43ucIiB7MoKq+BKWsqMCzNA0DvX5q2bAH81FSKC6CWISU=
    github_username: AgBhd0Z+W8UU+Hyif1IjkibOKXarjGdZGOgH7WjiOHOdMCNUNfSUomxjLNo2LEc0Utk4spaEJMsG4ZSgD4zLtW04SGfHxvSq3QRo8VILPwSy1NUcmLFMPULiYyb+uryEurRKXLs7qC1Kr2oTGP+eFatmIug8Bg9lLGe9Ecblwcxgcu1SzdqnAN1zOWO2gQjzHCmKP80UrWseLQnDVUhs5Gl6Vwy+i7ADosUxEB4GQEqckBSzn9ZqUQ+lMv0YbM89OqPW496eqfIgRrO8JtUSHgoHOPgCHTfqE4A9zVDZNqDwRMnzrdsC04ZT3iSOFDlXtDthS344TwfT5iVUZNG83iSw0gZudk0/V4ho8c5WAz62OYvMOe0QicM2x2T0w4AY0D789ZYhq40y+aULhUFV+B1VDuJkxJCdLJFxjHp42WAPEIP75GsHfaRjVULZRIAjB8g4m/jKyKvvzz26plHzGpKNw1XO2/Yj69aZBkaYf2VrV9yXcwNwSC4z195JpCc6zMAxighSI1eDGx/qPiTb85j8pyAslJ6uNJrCjkeG8Up8e5zEwTJc4iPU+64WWjGqkeg61m1BAJn+kVflAQ9BbPh9DPmi1VWLU3Z2FWJVHqaEJxCWlnFILKBuyV2jOHjBvxuVuTR8PAXpwuAB+SKV7PuRSsSNvXOwXzTIHLbUqHjXa4eS4q5VPGB996GA1z5RowsYsJcuBZXO324A7AFA/qE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        vault.buc.sh/vault-path: secret.saas.github
      name: vault-content-github
      namespace: default

