apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vault-content-cloudflare
  namespace: default
spec:
  encryptedData:
    cf_apikey_dnsedit: AgAiJYFMir9OcNNwvru2GAfY9+PfL06GrjJmwxDyO/R8jiCcPrLwXZZM2YtpK0Fv/mFXsTm8s82ZaMSABb2r+hX7hII+ML6XPGJ+p9+sNGZQpivAYyetJ3uL0wAFMiX1oRCJNkSvM0csthxTwx+fxgUQbXAuPf7aPFAt79SHQySNqu8WAW+xbU/Qh9/tqYOad177ZPWL0LC/9RGv8mWw97tPrfOVcnv9OPbmPLAAK4nERJJOFG4c8ldV4TDHXFwleEQTPFeOSsk1uQ2OxIwt2XA9HkTL5G1edM/f48GdffQBU++ALUYIlLG2mWCsorofLxvi+ezpogNDGososLVlYQy6fnEvnhsz65U1oyIEo3DWYql7HKSpbYXmp74eNt8+sw/acFZa4nsGKEOHkAugC1JKJ+NJDh2CnxCtf2Rt7r3JhqoLG4sQxhbwxATaIM/3l2U3DFn/CZ49ghb8KQ75Dcc2C+DFRiJj1+SM9RDDs3eR374+OkUMfPJSinM1MhHfwYNyhWXqn3y93TUe8n3NnK2kfBdo46OBbPxlrvlkLNgrcDGodQ11fNEH3zSX3E2LynEeSYIggbzptpvGwaUCnU4bhY79M6y/DiaQsHDkD3dzPPmRH8UKJ8fJouSwlY7yWBi5pm5GKZzV+5xIa22HGcd6Wv/LZCvd+IFUV/b/AgOeUaQXd9rJ++jsrkrPMivjvaAZ5MBmzoE=
    cf_tunnel_token: AgA9M4VbKcrLoaUovx2y/dll8Fn1uke7Ql3LILAZ3OPmQDr+zf0rypPY33cSSUX7rruY9UdMirr+mja1Jr53C63kC2qXgLLiKlib/RjvRo0i5wZUvZ5mMYInvg0NctVzfatMDLIEoWaEoi63lHFO0fLhN0IivYUq5paOP22zxSDSuAV6vRCo4mrh6tlmAd93QWnfukqizz95cDz/MOdJUfFMjMCGCke/w9ZpSQkXriER9XILbhoN/gPIL/wemEnF/Pqdq6N7TTdJLR7gFOI4FPLd1V8wrQ0zO2+YtalLzndQqkEzjuCCDJuZVj4WmvW9rggASUSaa0lc4zU/ZOUgiqrY1YiuKpSURMO5xI/5WZugFOIbXBregGQsrR5N7KCIKtY/D9GIMTn+PRk2uFwLjDyQ79JBhNFs7+RUFzP60cmC9gZzVv5f6yCngs6+XlCvwNZAmZRxRHlL+62CnhLK/3JCo2Lak9eMVX4FpUYvT3y7CyS6Zun+97HxgSrnFZUGRIgiJhe8B/08yT+T4l9X0SP5H13lrl0mlFIfDTDisTWs2/FP/bCGNAnzpf24vpHuvmp65h1OGQFienD9Mrc0/ZA9NVK6WsI5GFHmyldUegDrgoHeK7muKbHX7dyoRfWwt1ghT1bQ6+Hl3HTZ421pVwe5B8furBdoDuVk9dhay45/dnMyN/yoLpZBYBqx1nUn4UQWrQ0rsJE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        vault.buc.sh/vault-path: secret.saas.cloudflare
      name: vault-content-cloudflare
      namespace: default

