apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vault-content-cloudflare
  namespace: default
spec:
  encryptedData:
    cf_apikey_dnsedit: AgCLAVxBIR0nPPxlGIheAIHCurVcAmpYVbRgXBEGrGOZaAzB6M1rl5f65F4TWoLBoNOs+UWX78RNBx00MdXCL0AYoQT4yoZ81JNSBWJjpIDA3A0gFS9iYZZxjMI+xWpAc/haoZVN5qm9UhwKWJU95PO+akpqAx+pZzzkKJ61h/7NZenX+QXmM22yWfjZJMpI0nL7JmezfWGICQnnIgE2C/qN/Dd7Z3mW5ddq8KkbUon5lwz31YS88aQj5msKz3aL7x4xUMLIpmoFn3WSLLhtmsPT+LSK/ePyGglwh2Szkm7kOoEyNhPOZlwV56Ackxr0xPZOy/iSK2yZ6fiU7KPLqVF60fOSOx1jQ9AROSO6+00fmv5ys5FL6X4WC9HrZPRV/ov06T7gyDlVfpPZ8XJ6ift1a2s8ZA1ZHerWANQkAfAbjwkbRrQgAsTtnXzs14ijsuIAprKSEq79gwHEE9dgRtcNZLd12lsSkQKaFf3HWxDnzKM3s/M+U29szQJWNPlOntkBh2R86bpxF7gwGBwEjcWihCcatb+ZOAXWcyH6CiTfvmEwL69TpZhEapQm3tE2Hyw6T62lyaTAZ52K8oSub15PZZzlcfC192NVBEmTAlsEjjsqTNkE6L8GnrXTcL1pbHh7PPIRCvwiQOXLoUeBSa6u3NCF41cKw5gnDn/MBjySlFyYBn+6Dm/SQBSKF5XSRyYa6/YaP5SQFISeNY78aaZ7eHeEDuVKXMZxV0wGbJiOpBrayZUGkPME
    cf_tunnel_token: AgCDBgGtd9jtSuMZS1/eJ1XBtd0Crhdw/s0rIq8N1A2/pVwD4wuEcVkpFiLIja0yA1J03uiwnj0rfwaoKz349ASBapX9V5QZ/V2hsMds8cOPq5oUuppupmHY6GcrCPvyUVvrc7BBg6LqmuU51IgxyaQjAvwxHpDAI6HXykORSGYK5+XFjP4Ew46uYBM853Ow8FMGrpn1rDflVl5uFJ6bYexmDu9FfT0ElzXlTEv7Bufs2zTkPIUYrz0tZvKfmOAsdqSJFWATk/9bdn8EyhM/bReANTSNClDQfmvRbPFgMNJUi0ASZ2fJtqC1l3FsUsD5SZlMvSiUJfTTrxv7Xysb5lw1bfXvRKopjj1p2qJV7UUQG2cRxqtt1SeuK979/O5/6W9sK8ZUAwtIPJSScKEPL3q6BPvcf0zIqQgt/EXUDvtY0u3+uQcA7sNgFpONafUD/NDZXiaAPq34Bz0CdXsv4331JKaAgtj8bzDTyxRDzxQ5IdV6XviMSt1dYjxAw9wdtQq+eBM4a38y88iSs6ObyApACO0mT4CjtHIFkBlg0LCMfdD9fzQA5ZMftxUBJ+DwvQn/VClK1ddVMs0HwvelALpQDEc1omZy65FLDfCAe4aPYo5H5jOZ0zt3o1hxu0m4l7EXJ8a3G//zYAia9+fyfLDPoQi0Piuogu7Qh9FbI9YD4m2K5RLA099CU6YbScWKSBJCqZeBHzc=
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        vault.buc.sh/vault-path: secret.saas.cloudflare
      name: vault-content-cloudflare
      namespace: default

