apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vault-content-github
  namespace: default
spec:
  encryptedData:
    github_apikey_image_updater: AgCQOojl17I6BtFlwspsqOTq92W6MhHzmwUGVT0h2Ts+AoMZO82x2A3XY0V8FqSHQM8ewb9Qm/QAaqhJWIFQakLO1pdvASPrZd/xeblidIUi2J+GDAMV687F6oc1d9pxf3/2BcU++lcnJO2bEYYgiC0A534x6ykVUErrLDNMvXcZa1K9dLSj1ByvmGrNf0DmXeAZdB+NFPVcOmJ3UgdlLPUGB2T7khKDjahEg0DVdpU+rPm2gETaCnhPTZyCqux9tqzQG6L8EfffT7ttejHvTXkr30q01NNkhgSvmMpJYyXnWJdDkbH0K5uK3pj/HuqNNQIyC4nv0i/j2f2S0r4Z1pK7JZ+v4if0vXfUyE4RKN2ST8MpzWHbrEyTFhR/TK5URdS/yDCJoq/gYNHGAZWjLItfdjE0oBpOhvHzKmvt1SzCyebUBQ4Ic9zTikQPs0oQiSTRJw+N6+iN1VBaRr4TtTcJWw8cejDWlp8vEFXNoGlMKsDjnmQZDL1V9ADCAKXiB2kNGCeog0EKT4n7cKQUWjeUwTi1aa0jNEmDiZRoRQhJHnxYVRmdysYBPqvPjp9/tQCQpN+7iz1ghh+Q7wGZW+u0L9/DSNforz3kFkvh/abVCGH5hmr++oNwkOVmPQPR4YXQG+IKFACSBYfO4S2vWdbyMRWKBoYVD2h9f690W/jLO5Fzy27bmqfcFgT+FD69SIX8V+AC4+U=
    github_username: AgBzSGyd2RpxTUX0QDmWqHPTM0VyXjLCSz4kXuO5GFKVP76OVgZcuMDiEv9pSvLTr7eS9+sutK161QhZe1/JjJ8GV73yIQxmNF1v9QAagGpR1IiXBb6bhH+6CQH2JQ3FmXUP5J6k1VXNi9zEmTbHQICPCKJFlMUCOb6Jw2Qx1QgW7DtFpJhY8KgDcZS+1miTnzGlZMJ5BivlVvP9OMdpIs+ou42TzPu1mD8SP7qz3Rkgq8apZtJhkKzOhDEkL/R0x8Ew7qtO/fZ+LB9XyTsqjVH9Yowghs5jUEb5Bw8mXjU6iNRsU7NrqHpCjH2MGsv3pyiO6c5UhOAwOKGCwsdcCKlu0Xpa1vilPWIHXq2ov7feBXgEtLy7rREqjaCBLWORr5AnsSIKER6KIvLMSRQzgIhZXNl8Kp5dKTrJXzP+BGDbv9xN5i3v9j4JrtEMPO6Jc/V5YPQnjKY32GG6YCXmnd0n1nEdQjY8oK0tTwSewojbzDfxIFMnGS9ckea47EEQDYKJqmXSYcBO4RWX/y6wRhknNugxUD78HFCBXN37HfrMWwjuxwsSMNhsAz0S7kOok04PpqQajIvDjwUD7wSrqRhqz+qjvfe8n9QogDCthvv46JCkjrSUPdGlg9rgGYJ7Rh//lEbZLzIu1VutDd/0Gn1d6MTeeHCu84LVMfTBlZaY4YkmBNzfx5T6mhuUVqSWJdjpKQT4+Tg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        vault.buc.sh/vault-path: secret.saas.github
      name: vault-content-github
      namespace: default

