apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared
  namespace: default
spec:
  encryptedData:
    token: AgCFQ7yGfsSps9hNmA+qpQqWNFNkkorrqmdSCE1eMnX2geItCh2Mqz27VbrZRUOs1uAUKn4VA0DTFhYYHD6rFcR+cW/j1skTFCkU+uyeL9NQJ+NB3FLSIpZYZnTPyTwdNHixwnpAIpYLcBV+/cDaBCKweYnsyQnlFVIxouuK1mwnCZExhyvjHTK5Ee+XsPLtVyam6eosKVVFEBkeMIYhcIP9OtO4kS+L7HVbBrvTG88o7TneBpMCG39mvOx6eNnnmTZcajSO9AHdrir3JTykzrYdXALcZEuDcCq9HdW+Io/ej3O4+rKU/rFu9+fBMlhgEcmGgW19qlPIvYzMwqwWcAafu/qLh0tL/QKjINVBK4SOMLOHhLf6Fvq/9QmpsqCiRvHHbSJawTABrLIVzV/GooRIdf4naGbtIJfk7x1fvoqGxpehhP5zyLLcmec2Fut4cUaDp0ULh/B5PaIGDXHqE0zJ8rCTG54RTg6vMzryhxmQebUr4WLS9wq17EzLtM1oL+Juw+5gIvKDhSybaaFLg6ASAd4LmUpAgz8wWwdRD1YyGKTi6qMKWCZvBFquQVZGFR7oenl38VgdjR1tprGBHJURccbmJuKqNmPiaL6yI2BVvu1cIpZt2J8u1dMex/mIXWaM7cc1xRBbPtMcneyWvE+L6WaXhlsaxgHjp+8ey2TB3JGoFSWR+MDL5xMWIq2QyVPlnbHbm1C8KPXmECaCePjlIykK7ZVx3UsRIrxVD9JmYbxHgIXQ4I9Y7FkHQAFJDhbLN9rj3uVAeKkMnZ18sVer8Ft4wiG9tZ599Wa6Kb2dF3/vuEKwSsk4MkGPduU6uK20w96pHt4gRHLC+89RZu65KciaRbF29TmlcNJzvwY9WuzkLqpDZgJBQGKmdXb2JjVYxTxgNzlI0lLuxS8MonkxvGcrSy9H/mrEuKuZXEsHwA5C8K1Bm6uB
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflared
      namespace: default

