apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared
  namespace: default
spec:
  encryptedData:
    token: AgAOBBWnxfS/QJuZTGa+jhCaeP+1ltgEdIteeoITKzNlo0bYB+LlbejzrriaQc7EErcQd3FZJzV+BvcELgaTqVGViPP2eLYdXvXFHOhGm9VLP7utVYtnOf9Rkbl3lfrVtQrkP0uPAW6QqrzCRdAh6BnJ9YeeID0r4KqmYM+t7Vw8Zvn3D6YxrlUExH4UjFxzhT4StoUVrGZbvfxlahyXBLrqnSma09KT3gbogggkmKiXO5CCIbfwHU7k6VnJdxVwdxLl0c44QxYXKb9uZClcyiTEF3DyZuPH+s2a1bo1eJT257COiNzozXza6Q+Cnphfam8f8MMtmuzsH6hU+OKOoscbQYagx38a76cDytWtolhyaFUO1/rs5unZPuTb4SRESrIFTQ3aNVtO8NjrXZYUGBfIeRz+FZlxnOfNKWS+S02ZnZJ/lQZBaqKdIDDDa1/tffYb7HbvXUnwGwwfnfkoBkHchOEA1TE49E4Ra7H2OokkWJdVonpdwtPZz7grkKQPeFwEswjJFDItgFqF5myiOFhq2RY8kMIOj/SRaNnTcnxu1S1OXTneh3jM0T5/kpWB/b6tVRxIdiGsncSuDtdPhhJOBLUV13aXGHjHXar0rNzFq6fhqlbxzLaQsDfGkDtGgh2k4s1ifMOfaLZnGL7OJQYu6ANfle70ko2vjvoNJACbpqidYrZo9kFUMhFANOoSOL5L1QQimY2OV8T9eGJwIpmlXRDWDv3zjnQWnOHn/iwQzy/eZiv5GuFGLuoOSQTYEWDcgRLiLIN3R14OeaKT1MHxoM/o8ErqAOksTak7Zx3VlxwHiFgQq7scm6GG2FXqXlgcU66JMZMqU3pmGpMM8NTboMbHornzLFfIHiVDWiKaCXvZxkMiLqEr4DSJcsUDl9XxPpdoiMFiSqzo+8KtyDYbXy9cVPbBYtbzNkfGwN2bxcEazktdhjr6
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflared
      namespace: default

