apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared
  namespace: default
spec:
  encryptedData:
    token: AgClSJURTjmxqbcj7kNimkJfip2e8WGwSPSvVbs5zc0Z/tYSbdt8bEMPA/sQaHi0nQF5GthlOdjooi0BP1+LA5V33ilstrkopaklct2CmYffiEJ4bPnFnj2CR1qC/9x/bWNAY3dwgbB4bbFGGAFst2ly/8ajTYHLCgiHmecniw4MH4WOlGH35oThCBf7w6ivpzHJVdvjq2LlfzrWro7v8i+1WT6d7CxSpTrIpbBJqUiVFTW5d7e8Vj9MgSTKWvj2/P47WTnsGOFhyO8Y4HrJ01CpLWr41pK+MG/8zHk1As2cADGuj8QtgqVSOO7RAqXa/njhZpX0JP8fkUKYjZS307VeKuYoVWj3DxxlTJxkDpSE7qzg6uHAAW54wZz4rnP1fFl3dFA0g5oJNDKSP/T8oLGFGfn0z1X++IxbpQmaj3q/fWeEsojyMZscnA+emi5JEd5iNIPH4KZaULA8HKa7n6591wiaqpccHtEpkD4HX6a7Jn7T7Je+jr4/P11hEgtwM1Tyza4kULjCHx2C5JHjhbjtcSKXyHQ+a6dU5WsO1AVjuCRDzPg+dVI6FhhTDMe/rL5jkqlrij/2uVA/3/bYWa6cIvVDSE+Z0HB3gTGu1LFPTYVcv7QdlJk3/tpfHlHJJ/qKdDasrOq5uLkHvBVAuHbUXxoaUFBslrZsZW351oxg9RCZrg95Fng4TRtfhMlTO7LJGi43ww8STYohiv43BSVWEGiFNbpoRQt228jSG8tmg9/KSIKRNHyuo0W/e1wNlj5AiDU8/gs20NYC5C36mAzQC+9zuAPblvzYCdifCZ4hUmT9hK8yaJc3oEis363tfshfso/LA8LnveKjinXzI8TLDS5+zbX/lEltPgUxmpqSXiTCw+tf3B2rJzxNWivtJcrFkhg51OhB1YgSu1t0Q5t0xqF/rg1mK+5VMU5KxHPtQd6DRLirt7Hd
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflared
      namespace: default

