apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared
  namespace: default
spec:
  encryptedData:
    token: AgAHp+1t102vlZR7OGOGIGXXM5VJ5hfM/NoOJ5uvgM2AIojOSg3ttlcp/UxkavzfA5P/IvTFRR6Y0IEgQ6QOAJEAKWULHTPb2+zq12iHcNJ5ZrXG5SztShnht1FZA+SqEZQKGWXmPkmdRZ/c/ZsM2xHPp8hRSYIf5Qz9EqGu1XR6InwV88ylnGOcgx7HY35cxVBXa13yJtBOCJtXCfHS5AB5Qxy3ExnVUDLSn2CwJwIcUf2UE2B3FTcNWj87BigarLqRPkYw1NzZVplNo2MRJBUd5FRQ60uAdyD1DoGT+gBjiXkzlum63T8bUtK7H0adhJst2ov1IlKq8e2/Fgso4aUHvwgKAXYUqSgd9lG5izhdzKwlUrVOrYbs5X03Bmr3HYNKEesGn9ClhimjjDrL+SedORrfwrC0UugQM+wjqCzlTCD0f8SFYyf2o41rLNzT77b1dwGhsf3WKqaRixPz4GLcKtzfjc5UjMcMSPJRcb60N/hDjFnILTA7AI9hSAJ1lw9V+Hm/wMLoAEQKPOP4tSol+SdZgmQlCPG3Ru0caxXI9jw8oEjYDi3+cxiLJFzcVaUoMwtDopecBXRDBU/r1WPy6xdyG/wF3tg3bzM5zi2OwqQefoSt8CHb4culQ+ss7mE3HQqwoaDtBc3dRAsSsHJ1DuoQYhLmHMGBXl7XJBMfmRNSzP9ofqhFAol0zEGfveOlZNMqPLAiA03ITmacHgXeaO34Q1OFKfpdwNvCclK5GsAMYsafeFgcB5yoRysXSUxNpaRllqA19r9DCTUmgkKX626d5nNt0MeiXLdS7BEDd1eIZNZkFcQlTMqDw5r2GOsS3OcW9PGcW8Xu+K2s9XPh7gDeBG1R9wBr1MUxPsEY2fBBoDaKTN/X760xcduFYti3POV2oCV4KN3tQQWv8S5IxoUga49/JuDAPG4XuiYnEhMK5FsWuFlU
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflared
      namespace: default

