apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared
  namespace: default
spec:
  encryptedData:
    token: AgBwijM9b7FHJTGbaWxw76mlQX4AxmQZZ8SZtujTJoxQIvHanWyEejyoKw3mZIzeBH8BdAiRCXgMfwPqcHoEhmKUD0J9kXhHIqEXEEwJlS5ci1fGZ8WlBs+TMx0HI3oh1fBnwgR+2//nFT7AjVBYstFJgLgjpnAktcdbbV3XqMISiXWMiCkueduNwgJJoLNTgo4njp0pLYMo9kMj8QZcxvephoe1ovEswEt/FyZZoXPjigt/4YbxA7o1h+PYMl+QbZDP99DIada+vj0e/3dXECrUKksLAPERqy62WLO5rK9ZllWTC4cwwjHh31kK2FFXdgaAEs+xR58a0Y6zVOy9lJW746QYRkWKYe29b3mE1oXZSi2f+/u5v5HuBAHeCdXHm5KKKk0evvQgbkKQc87pgbeapwP3z/UrRald6LI17yR5uAwuYrFtOZSsIzvJjhvt/73rpZwI+ZAbcg6sVi5GgLKcap7bjgtt1scALfh7dm0eyqbxsDSpnuFG4pBntMemJcZlzAqACQoUJm0MGoMJBP7jsgvMVb0/Bhsk83g6Mr9l8z1L7SWarQNZaux3ZK9X76AweY+lOyaLIFqDP3GwXO6eXsKwpT5lJsoq8v7wtgvkJYMDsqf4poPSwLxLpwmTq1u4CgZyrS3uSK0F8ZWmRE0yZz/jZSCUYeUYZzDBJbJ/Rzvhpilr2doEmIH4Y2l6v2apmbUIYGHMvUvNORgJGJb9OYw0iga9JR+iImlg3uCPzYjM04KHp5G1kSEKc0f1GlUOSw2610M9BE428L3UT9VmlJUd5tK+qfIoR3JO+Sepdzis2enWMeJTurCIZWPrRBFISRexu1t6Yhn8lqErQrRjEJMy0cK627vPTg3+EsVfl7+yGexLUssrX8Qkyu37gT4cZ9hLHCnfRtB2TriP0SakgPmH1udlUh8bc02dWYMimoFhXZMWl5w7
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflared
      namespace: default

