# Declaring the user list
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: external-access
  namespace: kube-system
spec:
  basicAuth:
    secret: cloudflare-access

---
apiVersion: v1
kind: Service
metadata:
  name: nas
spec:
  type: ClusterIP
  ClusterIP: None
  ports:
  - name: web
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nas
Subsets:
- addresses:
  - ip: 10.0.0.19
  ports:
  - port: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: kvm
spec:
  type: ClusterIP
  ClusterIP: None
  ports:
  - name: admin
    port: 9090
    targetPort: 9090
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kvm
Subsets:
- addresses:
  - ip: 10.0.0.13
  ports:
  - port: 9090



---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-access
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: external-access@kubernetescrd
spec:
  rules:
  - host: nas-external.buc.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nas
            port:
              number: 8080
  - host: kvm-external.buc.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kvm
            port:
              number: 9090
