
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gatus
  namespace: flux-system
spec:
  interval: 24h
  url: https://minicloudlabs.github.io/helm-charts

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gatus-status
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare-dns
spec:
  tls:
  - hosts:
    - status.buc.sh
    secretName: cert-status-buc-sh
  rules:
  - host: status.buc.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gatus
            port:
              number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gatus-status-http
  namespace: default
spec:
  rules:
  - host: status.10.0.0.16.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gatus
            port:
              number: 80



---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatus
  namespace: flux-system
spec:
  interval: 5m
  releaseName: gatus
  targetNamespace: default
  chart:
    spec:
      chart: gatus
      version: '>=3.2.0'
      sourceRef:
        kind: HelmRepository
        name: gatus
        namespace: flux-system
  values:
    config:
      endpoints:
      - name: OKD Console
        group: evergreen
        url: http://okd-console:9000
        interval: 20m
        conditions:
          - "[STATUS] == 200"
      - name: PiHole
        group: evergreen
        url: http://pihole-web/admin/login.php
        interval: 1m
        conditions:
          - "[STATUS] == 200"
      - name: Vault
        group: evergreen
        url: http://vault:8200
        interval: 20m
        conditions:
          - "[STATUS] == 200"
      - name: TrueNAS - nas.buc.sh
        group: Hardware
        url: "https://10.0.0.20"
        insecure: true
        interval: 5m
        conditions:
          - "[STATUS] == 200"
      - name: QNAP
        group: Hardware
        url: "http://10.0.0.19:8080"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
      - name: KVM
        group: Hardware
        url: "https://10.0.0.19:9090"
        insecure: true
        interval: 5m
        conditions:
          - "[STATUS] == 200"
      - name: Gateway
        group: Hardware
        url: "http://10.0.0.1"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
      - name: Internet
        group: Hardware
        url: "https://1.1.1.1"
        interval: 5m
        conditions:
          - "[STATUS] == 200"

