
config:
  .unsafe: &unsafehttp
    interval: 5m
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"

  .webservice: &web
    interval: 20m
    conditions:
      - "[STATUS] == 200"

  metrics: true
  ui:
    title: LAB Status
    header: BUC LAB Status Page
    # logo:
    # link:
    # buttons: []

  endpoints:
  # evergreen
  - name: PiHole
    group: evergreen
    url: http://pihole-web/admin/login.php
    <<: *web
  - name: OKD Console
    group: evergreen
    url: http://okd-console:9000
    <<: *web
  - name: Vault
    group: evergreen
    url: http://vault:8200
    <<: *web

  # NAS
  - name: Unraid - nasv3.buc.sh
    group: NAS
    url: "https://10.0.0.19"
    <<: *web

  # Prod
  

  # Network
  - name: Internet
    group: Hardware
    url: "https://1.1.1.1"
    <<: *web
    interval: 1m
  - name: Gateway
    group: Hardware
    url: "http://10.0.0.1"
    <<: *web
    interval: 1m
  - name: KVM (Qemu) - kvm.buc.sh
    group: Hardware
    url: "https://10.0.0.13:9090"
    <<: *unsafehttp
  - name: H3 (oDroid) - h3.buc.sh
    group: Hardware
    url: "https://10.0.0.14:9090"
    <<: *unsafehttp
