metrics: true
ui:
  title: LAB Status
  header: BUC LAB Status Page
  # logo:
  # link:
  # buttons: []

endpoints:
- name: Internet
  group: Hardware
  url: "https://1.1.1.1"
  interval: 5m
  conditions:
    - "[STATUS] == 200"
- name: Gateway
  group: Hardware
  url: "http://10.0.0.1"
  interval: 1m
  conditions:
    - "[STATUS] == 200"
- name: TrueNAS - nas.buc.sh
  group: Hardware
  url: "https://10.0.0.20"
  interval: 5m
  client:
    insecure: true
  conditions:
    - "[STATUS] == 200"
- name: QNAP
  group: Hardware
  url: "http://10.0.0.19:8080"
  interval: 5m
  conditions:
    - "[STATUS] == 200"
- name: KVM
  group: Hardware
  url: "https://10.0.0.19:9090"
  interval: 5m
  client:
    insecure: true
  conditions:
    - "[STATUS] == 200"
- name: PiHole
  group: evergreen
  url: http://pihole-web/admin/login.php
  interval: 20m
  conditions:
    - "[STATUS] == 200"
- name: OKD Console
  group: evergreen
  url: http://okd-console:9000
  interval: 20m
  conditions:
    - "[STATUS] == 200"
- name: Vault
  group: evergreen
  url: http://vault:8200
  interval: 20m
  conditions:
    - "[STATUS] == 200"
