apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- authelia-helm.yaml

secretGenerator:
- name: authelia-values
  files:
  - values.yaml

generatorOptions:
  disableNameSuffixHash: true
