apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: Vault
metadata:
  name: vault
spec:
  externalConfig:
    startupSecrets:
      - type: kv
        path: secret/data/saas/cloudflare
        data:
          secretKeyRef:
          - name: vault-content-cloudflare
            key: cf_tunnel_token
            optional: true
          - name: vault-content-cloudflare
            key: cf_apikey_dnsedit
            optional: true
      - type: kv
        path: secret/data/saas/github
        data:
          secretKeyRef:
          - name: vault-content-github
            key: github_username
            optional: true
          - name: vault-content-github
            key: github_apikey_image_updater
            optional: true
      - type: kv
        path: secret/data/access/static-cred
        data:
          secretKeyRef:
          - name: common-secrets
            key: cred_description
            optional: true
          - name: common-secrets
            key: cred_admin_user
            optional: true
          - name: common-secrets
            key: cred_admin_password
            optional: true
          - name: common-secrets
            key: cred_user_user
            optional: true
          - name: common-secrets
            key: cred_user_password
            optional: true
      - type: kv
        path: secret/data/access/secret-ids
        data:
          secretKeyRef:
          - name: vault-content-secretids
            key: prod
            optional: true
      - type: kv
        path: secret/data/access/nas
        data:
          secretKeyRef:
          - name: common-secrets
            key: iscsi_user
            optional: true
          - name: common-secrets
            key: iscsi_password
            optional: true
          - name: common-secrets
            key: s3_accesskey
            optional: true
          - name: common-secrets
            key: s3_secretkey
            optional: true
          - name: common-secrets
            key: s3_ro_accesskey
            optional: true
          - name: common-secrets
            key: s3_ro_secretkey
            optional: true
      - type: kv
        path: secret/data/access/syncthing
        data:
          secretKeyRef:
          - name: vault-content-syncthing
            key: apikey
            optional: true
          - name: vault-content-syncthing
            key: tls.crt
            optional: true
          - name: vault-content-syncthing
            key: tls.key
            optional: true
      - type: kv
        path: cluster/data/cert/cert-paste-buc-sh
        data:
          secretKeyRef:
          - name: cert-paste-buc-sh
            key: tls.crt
            optional: true
          - name: cert-paste-buc-sh
            key: tls.key
            optional: true
      - type: kv
        path: cluster/data/cert/cert-argocd-buc-sh
        data:
          secretKeyRef:
          - name: cert-argocd-buc-sh
            key: tls.crt
            optional: true
          - name: cert-argocd-buc-sh
            key: tls.key
            optional: true
      - type: kv
        path: cluster/data/cert/cert-grafana-buc-sh
        data:
          secretKeyRef:
          - name: cert-grafana-buc-sh
            key: tls.crt
            optional: true
          - name: cert-grafana-buc-sh
            key: tls.key
            optional: true
      - type: kv
        path: cluster/data/cert/cert-paperless-buc-sh
        data:
          secretKeyRef:
          - name: cert-paperless-buc-sh
            key: tls.crt
            optional: true
          - name: cert-paperless-buc-sh
            key: tls.key
            optional: true
      - type: kv
        path: cluster/data/cert/cert-syncthing-buc-sh
        data:
          secretKeyRef:
          - name: cert-syncthing-buc-sh
            key: tls.crt
            optional: true
          - name: cert-syncthing-buc-sh
            key: tls.key
            optional: true
      - type: kv
        path: cluster/data/cert/cert-files-buc-sh
        data:
          secretKeyRef:
          - name: cert-files-buc-sh
            key: tls.crt
            optional: true
          - name: cert-files-buc-sh
            key: tls.key
            optional: true
      - type: kv
        path: cluster/data/cert/cert-r2-buc-sh
        data:
          secretKeyRef:
          - name: cert-r2-buc-sh
            key: tls.crt
            optional: true
          - name: cert-r2-buc-sh
            key: tls.key
            optional: true
      - type: kv
        path: cluster/data/cert/cert-secure-http-buc-sh
        data:
          secretKeyRef:
          - name: cert-secure-http-buc-sh
            key: tls.crt
            optional: true
          - name: cert-secure-http-buc-sh
            key: tls.key
            optional: true
      - type: kv
        path: cluster/data/cert/apiserver
        data:
          data:
            ca_cert: "${env `CA_CERT`}"
  envsConfig:
    - name: CA_CERT
      valueFrom:
        configMapKeyRef:
          name: kube-root-ca.crt
          key: ca.crt
          optional: true