apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: Vault
metadata:
  name: vault
spec:
  externalConfig:
    startupSecrets:
      - type: kv
        path: secret/data/saas/cloudflare
        data:
          secretKeyRef:
          - name: vault-content-cloudflare
            key: cf_tunnel_token
            optional: true
          - name: vault-content-cloudflare
            key: cf_apikey_dnsedit
            optional: true
      - type: kv
        path: secret/data/saas/github
        data:
          secretKeyRef:
          - name: vault-content-github
            key: github_username
            optional: true
          - name: vault-content-github
            key: github_apikey_image_updater
            optional: true
      - type: kv
        path: secret/data/access/static-cred
        data:
          secretKeyRef:
          - name: common-secrets
            key: cred_description
            optional: true
          - name: common-secrets
            key: cred_admin_user
            optional: true
          - name: common-secrets
            key: cred_admin_password
            optional: true
          - name: common-secrets
            key: cred_user_user
            optional: true
          - name: common-secrets
            key: cred_user_password
            optional: true
      - type: kv
        path: secret/data/access/secret-ids
        data:
          secretKeyRef:
          - name: vault-content-secretids
            key: prod
            optional: true
      - type: kv
        path: cluster/data/cert/cert-paste-buc-sh
        data:
          secretKeyRef:
          - name: cert-paste-buc-sh
            key: tls.crt
            optional: true
          - name: cert-paste-buc-sh
            key: tls.key
            optional: true
      - type: kv
        path: cluster/data/cert/cert-argocd-buc-sh
        data:
          secretKeyRef:
          - name: cert-argocd-buc-sh
            key: tls.crt
            optional: true
          - name: cert-argocd-buc-sh
            key: tls.key
            optional: true
      - type: kv
        path: cluster/data/cert/apiserver
        data:
          data:
            ca_cert: "${env `CA_CERT`}"
      # - type: kv
      #   path: secret/data/cluster/s3/vault
      #   data:
      #     secretKeyRef:
      #     - name: vault-s3
      #       key: access_key
      #       optional: true
      #     - name: vault-s3
      #       key: secret_key
      #       optional: true
  envsConfig:
    - name: CA_CERT
      valueFrom:
        configMapKeyRef:
          name: kube-root-ca.crt
          key: ca.crt
          optional: true