apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vault-content-cloudflare
  namespace: default
spec:
  encryptedData:
    cf_apikey_dnsedit: AgBhkF7NbNjnfH39J/YmWgsC1WGqjFhHI8xozRytp8zDFDC5c+bjoYhBY/nUQvJF9A2V7XdhV2jqcz1Lz8cPL+LAWufnpAPClb8bQxYCTcOHmsNmR2kxqnuZsfg3eFEGS8aMnA6hfnvIXfn6j4f6sCOY5cUzaZXQbGUWquDp/Pd7RIZNvhvbmvU+aL9+831hHrTJwlXZnrH45jfSoKR9x5zq//tIHGwEd51vTI5MTDHcfZLhsTjzLY3v8Gpxi6x1Tz7hbCrHB4vXQf4nDY0Rhs39WrO/PhC25i0nHQochWnaD/vwpyMmTrR1T1yIUZwPQ9HonNqXSvutyCNIFRHkubQMqFqYpiShMgB/msM1kFVW20VWtxbX2rwT2y6Pp1ZkYCii/QcwZbp9RPjGcfl7lvYJLHJ/rcJUdXHX4iULgD7Gg4RFUyIaNysttv+sReg8mPFFuc6I/vWmfhJKmDekxGvgeVjXDkRFfWetqQwGNbt3di64mzj97nx5MzC7Gan8ChtQUR3N4gViHco9FG7HcYb/l4NC25Ik+Q0a/IGuURmRWc35woJcPp1CybV7Pv6wovs0oTOQ/zezXEZmLgcOK4gCtJx4k27CxF5oKhetc+nKwN9H2eI7zCImXkr2/AVfdb/PhuoMGlbsrbsHHHoDlzI/Uwn3vYgv2C+HIY5CN4ruRrqR2FqNFqtAJQkUE29Og9gM/p6Lm5bVj9G4HY5oceqpqjSWYfO+lGUb+Xzn5987KPVmiBWf3tjE
    cf_tunnel_token: AgC5R2+g6iLosqBgeuFVM9nrXOevsJdftHlsU+WV2luLitQzWcUfqbLohTurXDxJIwvEc+4E16hn6Jwhbo+HkBkha+v1RD80EFQpfaVzWfJVfO5hQ/PxFNf0ViTcdj5pgMnp+DfvYAme+5CJae8aBFDd/+je6nBwYhkwXWbacoRWIRKs06w/14TvOJ6Nv1k+cDfNPaK2lqnmfF6vzo7YvMwHGgbm8+TOGywpTCo81nEe5ED6jBaGNZwosuQGtX65LdFWnM7QivZChoFQB6R1xZuJ7rhaJBWcbm1zFtvkaChC5RyTUMgOXquBMeAmHtZupmGId9xFS3BurHUJTMSkuNSB/4G9aLxskC+35l2EF58nzJLQPBiVMUrpm41ZRAcESaScFuSbJ3IHu4Ge/7ZhdJMalZ9X/aKLUNazGMQo1X8q7L+uSJgrCYlAsBX95V1o7KqGyYtYhpcXwF2jJW6OWQAbWQn10Ocr4ck+VnP4GOx9CRFe07vUfYkJWF23jyCTnTMwxcCGWBKjN88lGQxLHQzM35vSmi0g3fu2j+lZS8qv4qgL+VPBN/G9TnA8kudvf4yqgLl6lj8DZ2++I5+275HBbAo+IZ05B2fkkArLuj1sPwS+S2Fb9xBHJBFqS1tl5vF9b0h4SDLW8HZdi7sF7c2aeLmD38eLOfr/gbn66EyRgEQ4+6/VBXsveGa02/GW2jw9QDtm32JYFB4OOrg903qAHlLKNnMywsRQC7hnFbrIECnec51CGwatR949+a3AEi5LhXnmvOIyUYC/jrV3HiFL8GM9DGP8EaYUA1fO37xI/VoMc3kdIi9WjDH4UA1QJ5+gRektuNsChslw8RJmcwAtxXoHFr8MvgARyW+Q9tuuVEHzdaTnh+z/LY3G5A/Ps+DOJT79P8nb9Gm7QC0PXcOg8s6elEUEXIXdViSlRGz1arMRBT1L5Dx4
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        vault.buc.sh/update-action: restart
        vault.buc.sh/vault-path: secret.saas.cloudflare
      name: vault-content-cloudflare
      namespace: default

