
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: node-exporter
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: flux-system
spec:
  interval: 5m
  releaseName: node-exporter
  targetNamespace: default
  chart:
    spec:
      chart: node-exporter
      version: '>=3.0.0'
      sourceRef:
        kind: HelmRepository
        name: node-exporter
        namespace: flux-system
      interval: 5m
  values: {}
