
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: node-exporter
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: default
  chart:
    spec:
      chart: node-exporter
      version: '>=3.0.0'
      sourceRef:
        kind: HelmRepository
        name: node-exporter
        namespace: flux-system
      interval: 5m
  values: {}


---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: default
  chart:
    spec:
      chart: metrics-server
      version: '>=5.0.0'
      sourceRef:
        kind: HelmRepository
        name: node-exporter
        namespace: flux-system
      interval: 5m
  values: {}