apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: node-exporter
  namespace: kube-system
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: node-exporter
  targetNamespace: default
  valuesContent: |-
    image:
      tag: "latest"
    