apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: k8s-vault-secret
spec:
  provider:
    vault:
      server: "http://vault:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "readwrite"
          serviceAccountRef:
            name: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: k8s-vault-cluster
spec:
  provider:
    vault:
      server: "http://vault:8200"
      path: "cluster"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "reareaderdwrite"
          serviceAccountRef:
            name: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: k8s-vault-public
spec:
  provider:
    vault:
      server: "http://vault:8200"
      path: "public"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "readwrite"
          serviceAccountRef:
            name: external-secrets

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-local
spec:
  provider:
    kubernetes:
      remoteNamespace: default
      server:
        url: "http://kubernetes.default.svc"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: default
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets