
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: common-secrets
  namespace: default # Same of the SecretStores
spec:
  updatePolicy: Replace # Policy to overwrite existing secrets in the provider on sync
  deletionPolicy: Delete # the provider' secret will be deleted if the PushSecret is deleted
  refreshInterval: 10s # Refresh interval for which push secret will reconcile
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: k8s-vault-secret
      kind: ClusterSecretStore
  selector:
    secret:
      name: common-secrets
  data:
  - match:
      secretKey: cred_description
      remoteRef:
        remoteKey: access/static-cred
        property: cred_description
  - match:
      secretKey: cred_admin_user
      remoteRef:
        remoteKey: access/static-cred
        property: cred_admin_user
  - match:
      secretKey: cred_admin_password
      remoteRef:
        remoteKey: access/static-cred
        property: cred_admin_password
  - match:
      secretKey: cred_user_user
      remoteRef:
        remoteKey: access/static-cred
        property: cred_user_user
  - match:
      secretKey: cred_user_password
      remoteRef:
        remoteKey: access/static-cred
        property: cred_user_password
  - match:
      secretKey: iscsi_user
      remoteRef:
        remoteKey: access/nas
        property: iscsi_user
  - match:
      secretKey: iscsi_password
      remoteRef:
        remoteKey: access/nas
        property: iscsi_password
  - match:
      secretKey: s3_accesskey
      remoteRef:
        remoteKey: access/nas
        property: s3_accesskey
  - match:
      secretKey: s3_secretkey
      remoteRef:
        remoteKey: access/nas
        property: s3_secretkey
  - match:
      secretKey: s3_ro_accesskey
      remoteRef:
        remoteKey: access/nas
        property: s3_ro_accesskey
  - match:
      secretKey: s3_ro_secretkey
      remoteRef:
        remoteKey: access/nas
        property: s3_ro_secretkey
