apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vault-content-github
  namespace: default
spec:
  encryptedData:
    github_apikey_image_updater: AgAoSLzmsIZkjgfZi2U3U5AnOYrEwiTfu6VQMZ8QcvGPu3dhXiI7ZzpZadrkCr0oH4lNvE0N++j7RmCeKqItw7M0ohanqoDxMcQ34T8GYTtlaECrq9KE0FVQwtoKwddA2yaObpr9fueY9hv+XiS9fz3imxpXO7GEzqiYNF5v4KdUZ7TOwLHY1tYm1tptqlt+hvJBJx1vf7WeF/oYBq5GuanKEqwUput4hJ6kv06AKmm8yXYvEGEoxPHBPy5S6w1+jdOQ7u/TNBcJu4gZtt/cxj1J2GMEISUEVsfh90V7wIwFR8AYLJR1feZ3tSH/DZj5mIlgMSxMw0KPSdlzK/jfA+2fEchy4Uwgl9rgYtIB3IaNdW0QW0IT7I774WeUwJDll6HalbK3QW8Fej+a9hO3QKXf8vOuGOBJkP+sUUbBV+i9sVEYVfqkN0Oc9IgOQR4rLOD+fMO6xHOfI+H4lwOmAQRDsHZfG9sG+jZEOdxZbwj2/8A/hvL8lZ8Cnel7qPQYyTvrqKYILU9CI/I8Kw+IX//KKgph2PVZjxnjiHg8ZtCEwA8HXYCaN3yv871KjYsNv1WAHtMsidnkCkuoLrwYKRUSMm8ioGVaxqbVB+wlr+ufJXk2P7DGnU8xyFE5eYfW+CVrHZsStlHsAAbvmf12ptIUSVuJ+gi8WhaaqrdL1dp3KU8xswtGnFTwKVrzsfdTiBX4mt5jt/g=
    github_username: AgB1hJSeVowxuNdytZEalY8scFnwTD4YINaZb/CzWYOnJqJF1R+0YiugoY2pXHwvCaUWG6Re/BzeggHa4cxwcx+8Dvg959Rt77EyuUlUtCnNag5FCGgJq46XIFtkYEwACgp4iwOErUQJCNp4UPO3YGG3DVaOvzaw7FZRIA57/t0VKbu2Vz153Drc1E8ifqQxjYD6+7EWjChYYUj30+2eQFit2hzeWjRn6Te5MdhxAiP80X/yUR4tOclJERzFq/5oe9uwxFmLlQeqh+cVVioc2c4dzgsoT2498Gkmr/FcP7eqV6NmCzY2cHU21rMzlgQB3ONYqhKxhDDgnHpsCEsksQma3jiKgH6DUoG51e5ZmYMbpml0ek5LWHie9hg9eGo4YMcvwmjdmXPM1VWJEavjBiTV0ktNdjrMzJ5dHR2EkzyB0d7W2tcCrxDqOiHzKTFdwwegeYjZ57EwtqQw+jBZHBCqDKwzE7Tp7noFzvxkJISdAEMVwdpa/f0f+CL7I9idn4FKbL4qNa+QGraafb1Dz/QcaXx35i2fJbAe5sRA7BogE9IpoSPogIfAfCIKuI4EICbRFsR2I8PlYrj3ljZqSwltZ5agLrBv7ZwuiJCTaP142TLlWTazsNjkrkLHbBgZ+NXShEipkeRJ18NEE/MkmQLN2PGubdqCVPZ37WyJ7KOJz/dG2mXstEpaJgp6ffhoxpbfePECROdQdj/jnYYh0ro=
  template:
    metadata:
      creationTimestamp: null
      # labels:
      #   vault.buc.sh/update-action: restart
      #   vault.buc.sh/vault-path: secret.saas.github
      name: vault-content-github
      namespace: default

---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: vault-content-github
  namespace: default
spec:
  updatePolicy: Replace
  deletionPolicy: Delete # the provider' secret will be deleted if the PushSecret is deleted
  refreshInterval: 3600s # Refresh interval for which push secret will reconcile
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: k8s-vault-secret
      kind: ClusterSecretStore
  selector:
    secret:
      name: vault-content-github
  data:
  - match:
      remoteRef:
        remoteKey: saas/github # Remote reference (where the secret is going to be pushed)