issuer: https://dex.buc.sh
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556
  # tlsCert: /etc/dex/tls/tls.crt
  # tlsKey: /etc/dex/tls/tls.key
connectors: []

oauth2:
  skipApprovalScreen: true
  alwaysShowLoginScreen: false
  # Allow password grants with local users
  passwordConnector: local

staticClients:
- id: login
  name: "SSO Login Applications"
  secret: notaSecretDexisLocal
  redirectURIs:
  # kubectl
  - 'http://localhost:8000'
  # HeadLamp
  - 'http://homelab-console.10.0.0.23.nip.io/oidc-callback'
  - 'http://homelab-console.buc.sh/oidc-callback'
  # ArgoCD ???
  # - 'http://argocd.10.0.0.23.nip.io/applications'
  # - 'http://argocd.10.0.0.23.nip.io/api/dex/callback'
  # - 'http://argocd.10.0.0.23.nip.io/auth/login'
  # r2.buc.sh (S3 Frontend)
  - https://r2.buc.sh/oauth2/callback
  # Grafana
  - https://grafana.buc.sh/login/generic_oauth
  # Matrix
  - https://matrix.cloud.buc.sh/_synapse/client/oidc/callback

enablePasswordDB: true
staticPasswords:
- email: "admin@buc.sh"
  username: "admin"
  userID: "1"
  hash: "{{ .Env.USER_ADMIN_HASH }}"
- email: "but@buc.sh"
  username: "Bot"
  userID: "2"
  hash: "{{ .Env.USER_BOT_HASH }}"
