apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ddns-config-secrets
spec:
  secretStoreRef:
    name: k8s-vault
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: test-exteral-secret
  # Data defines the connection between the Kubernetes Secret keys and the Provider data
  data:
    - secretKey: DDNS_CF_TOKEN
      remoteRef:
        key: secret/saas/cloudflare
        property: cf_apikey_dnsedit
