apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ddns-config-secrets
spec:
  secretStoreRef:
    name: k8s-vault
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    # DeletionPolicy defines how/when to delete the Secret in Kubernetes
    deletionPolicy: "Delete"
    template:
      # Use inline templates to construct your desired config file that contains your secret
      data:
        DDNS_CF_TOKEN: "{{ .data.apikey }}"

  # Data defines the connection between the Kubernetes Secret keys and the Provider data
  data:
    - secretKey: apikey
      remoteRef:
        key: secret/saas/cloudflare
        property: cf_apikey_dnsedit
