---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: common
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
  - name: sealed-secrets
  path: ./gitops/common
  prune: true
  sourceRef:
    kind: GitRepository
    name: voodoo-gitops
