---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets-operator
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./gitops/external-secrets/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: voodoo-gitops
  targetNamespace: default

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./gitops/external-secrets
  prune: true
  dependsOn:
  - name: external-secrets-operator
  sourceRef:
    kind: GitRepository
    name: voodoo-gitops
  targetNamespace: default
