---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-state-metrics
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./gitops/kube-state-metrics
  prune: true
  sourceRef:
    kind: GitRepository
    name: voodoo-gitops
