---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: okd-console
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./gitops/okd-console
  prune: true
  sourceRef:
    kind: GitRepository
    name: voodoo-gitops
  targetNamespace: default
