---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pihole
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./gitops/pihole
  prune: true
  sourceRef:
    kind: GitRepository
    name: voodoo-gitops