---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: shell-ddns
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-config
  interval: 1m0s
  path: ./gitops/shell-ddns
  prune: true
  sourceRef:
    kind: GitRepository
    name: voodoo-gitops
  targetNamespace: default
