---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sidero-machines
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./gitops/sidero-machines
  prune: true
  sourceRef:
    kind: GitRepository
    name: voodoo-gitops
