---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-stuff
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./gitops/stuff/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: voodoo-gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-stuff-eso-auth
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./gitops/stuff/prod-eso
  prune: true
  sourceRef:
    kind: GitRepository
    name: voodoo-gitops
