---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-operator-helm
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./gitops/vault/helm
  prune: true
  sourceRef:
    kind: GitRepository
    name: voodoo-gitops
  targetNamespace: default

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-instance
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
  - name: vault-operator-helm
  path: ./gitops/vault/
  prune: true
  sourceRef:
    kind: GitRepository
    name: voodoo-gitops
  targetNamespace: default

