---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-terraform
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./gitops/vault-terraform
  prune: true
  sourceRef:
    kind: GitRepository
    name: voodoo-gitops
  targetNamespace: flux-system
