---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault-terraform
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
  - name: vault-instance
  path: ./gitops/vault-terraform/kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: voodoo-gitops
  targetNamespace: default
