---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wastebin
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./gitops/wastebin
  prune: true
  sourceRef:
    kind: GitRepository
    name: voodoo-gitops
  targetNamespace: default
