---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-argocd-buc-sh
  namespace: prod
spec:
  secretName: cert-argocd-buc-sh
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - buc
  dnsNames:
    - argocd.buc.sh
  issuerRef:
    name: letsencrypt-prod-cloudflare-dns
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-secure-http-buc-sh
  namespace: prod
spec:
  secretName: cert-secure-http-buc-sh
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - buc
  commonName: '*.cloud.buc.sh'
  dnsNames:
    - '*.cloud.buc.sh'
  issuerRef:
    name: letsencrypt-prod-cloudflare-dns
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-grafana-buc-sh
  namespace: prod
spec:
  secretName: cert-grafana-buc-sh
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - buc
  dnsNames:
    - grafana.buc.sh
  issuerRef:
    name: letsencrypt-prod-cloudflare-dns
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-paperless-buc-sh
  namespace: prod
spec:
  secretName: cert-paperless-buc-sh
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - buc
  dnsNames:
    - paperless.buc.sh
  issuerRef:
    name: letsencrypt-prod-cloudflare-dns
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-prod-console-buc-sh
  namespace: prod
spec:
  secretName: cert-prod-console-buc-sh
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - buc
  dnsNames:
    - prod-console.buc.sh
  issuerRef:
    name: letsencrypt-prod-cloudflare-dns
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-push-buc-sh
  namespace: prod
spec:
  secretName: cert-push-buc-sh
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - buc
  dnsNames:
    - push.buc.sh
  issuerRef:
    name: letsencrypt-prod-cloudflare-dns
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-r2-buc-sh
  namespace: prod
spec:
  secretName: cert-r2-buc-sh
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - buc
  dnsNames:
    - r2.buc.sh
  issuerRef:
    name: letsencrypt-prod-cloudflare-dns
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-syncthing-buc-sh
  namespace: prod
spec:
  secretName: cert-syncthing-buc-sh
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - buc
  dnsNames:
    - syncthing.buc.sh
  issuerRef:
    name: letsencrypt-prod-cloudflare-dns
    kind: ClusterIssuer
    group: cert-manager.io