
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-push-buc-sh
  namespace: default
spec:
  secretName: cert-push-buc-sh
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - buc
  dnsNames:
    - push.buc.sh
  issuerRef:
    name: letsencrypt-prod-cloudflare-dns
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cert-push-buc-sh
  namespace: default # Same of the SecretStores
spec:
  updatePolicy: Replace # Policy to overwrite existing secrets in the provider on sync
  deletionPolicy: Delete # the provider' secret will be deleted if the PushSecret is deleted
  refreshInterval: 10s # Refresh interval for which push secret will reconcile
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: k8s-vault-cluster
      kind: ClusterSecretStore
  selector:
    secret:
      name: cert-push-buc-sh
  data:
  - match:
      remoteRef:
        remoteKey: cert/cert-push-buc-sh # Remote reference (where the secret is going to be pushed)
