
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: common-secrets-to-prod
  namespace: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-local
    kind: ClusterSecretStore
  target:
    name: static-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: common-secrets
